services:
  db:
    image: postgres:18.1-trixie
    restart: always
    environment:
      - POSTGRES_DB=postgres-sync-demo
      - POSTGRES_USER=postgres-sync-demo
      - POSTGRES_PASSWORD=postgres-sync-demo
    ports:
      - '55677:5432'
